fn main() {
    cc::Build::new()
        .file("soxr/cr.c")
        .file("soxr/cr32.c")
        .file("soxr/soxr.c")
        .file("soxr/dbesi0.c")
        .file("soxr/filter.c")
        .file("soxr/data-io.c")
        .file("soxr/fft4g32.c")
        .file("soxr/fft4g64.c")
        .file("soxr/pffft-wrap.c")
        // These are included by other C Files.
        // SIMD!
//.file("soxr/fft4g.c")
//.file("soxr/pffft.c")
//.file("soxr/cr-core.c")
//.file("soxr/ui")
        .warnings(false)
        .extra_warnings(false)
        .flag("-w")
        .define("AVCODEC_FOUND", Some("0"))
        .define("AVUTIL_FOUND", Some("0"))
        .define("WITH_PFFFT", Some("1"))
        .define("HAVE_FENV_H", Some("1"))
        .define("HAVE_LRINT", Some("1"))
        .define("HAVE_BIGENDIAN", Some("0"))
        .define("WITH_CR32", Some("1"))
        .define("WITH_CR32S", Some("0"))
        .define("WITH_VR32", Some("0"))
        .define("WITH_HI_PREC_CLOCK", Some("1"))
        .define("WITH_FLOAT_STD_PREC_CLOCK", Some("0"))
        .define("WITH_DEV_TRACE", Some("0"))
        .define("SOXR_LIB", Some("1"))
        .compile("soxr");
}
